name: go-cafeteria
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_HOST: rdb # 下でrdbという名前でpostgresコンテナを立てているのでこれが解決できる
      PG_PORT: 5432
      PG_USER: user
      PG_PASSWORD: ${DB_PASSWORD:?required}
      PG_DB: cafeteria
    depends_on:
      rdb:
        condition: service_healthy

  rdb:
    image: postgres:17
    ports:
      - "127.0.0.1:5432:5432" #ホストのポート:コンテナのポート
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD:?required}
      POSTGRES_DB: cafeteria
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cafeteria"]
      interval: 2s
      timeout: 3s
      retries: 15
volumes:
  db-store:
