// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package store

import (
	"context"
)

const countMenus = `-- name: CountMenus :one
SELECT count(*) FROM menus
`

func (q *Queries) CountMenus(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMenus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menus (name, description, price_yen, stock) VALUES($1,$2,$3,$4) RETURNING id, name, description, price_yen, stock, created_at, updated_at
`

type CreateMenuParams struct {
	Name        string
	Description string
	PriceYen    int32
	Stock       int32
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, createMenu,
		arg.Name,
		arg.Description,
		arg.PriceYen,
		arg.Stock,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceYen,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenu = `-- name: GetMenu :one
SELECT id, name, description, price_yen, stock, created_at, updated_at FROM menus WHERE id = $1
`

func (q *Queries) GetMenu(ctx context.Context, id int64) (Menu, error) {
	row := q.db.QueryRowContext(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceYen,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMenus = `-- name: ListMenus :many
SELECT id, name, description, price_yen, stock, created_at, updated_at FROM menus ORDER BY id
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.QueryContext(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Menu
	for rows.Next() {
		var i Menu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceYen,
			&i.Stock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menus SET name=$2, description=$3, price_yen=$4, stock=$5 WHERE id=$1 RETURNING id, name, description, price_yen, stock, created_at, updated_at
`

type UpdateMenuParams struct {
	ID          int64
	Name        string
	Description string
	PriceYen    int32
	Stock       int32
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, updateMenu,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceYen,
		arg.Stock,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceYen,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMenuPrice = `-- name: UpdateMenuPrice :one
UPDATE menus SET price_yen=$2 WHERE id=$1 RETURNING id, name, description, price_yen, stock, created_at, updated_at
`

type UpdateMenuPriceParams struct {
	ID       int64
	PriceYen int32
}

func (q *Queries) UpdateMenuPrice(ctx context.Context, arg UpdateMenuPriceParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, updateMenuPrice, arg.ID, arg.PriceYen)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceYen,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMenuStock = `-- name: UpdateMenuStock :one
UPDATE menus SET stock=$2 WHERE id=$1 RETURNING id, name, description, price_yen, stock, created_at, updated_at
`

type UpdateMenuStockParams struct {
	ID    int64
	Stock int32
}

func (q *Queries) UpdateMenuStock(ctx context.Context, arg UpdateMenuStockParams) (Menu, error) {
	row := q.db.QueryRowContext(ctx, updateMenuStock, arg.ID, arg.Stock)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceYen,
		&i.Stock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
