// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Menu struct {
	ID          int64
	Name        string
	Description string
	// 税抜き価格(円)
	PriceYen int32
	// 当日提供可能な数
	Stock     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID    uuid.UUID
	Email string
	// 表示名
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserPassword struct {
	UserID       uuid.UUID
	PasswordHash string
	UpdatedAt    time.Time
}
