// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type Menu struct {
	ID          int64
	Name        string
	Description string
	// 税抜き価格(円)
	PriceYen int32
	// 当日提供可能な数
	Stock     int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
