// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_password.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPasswordHash = `-- name: CreatePasswordHash :one
INSERT INTO user_passwords (user_id, password_hash) VALUES($1,$2) RETURNING user_id, password_hash, updated_at
`

type CreatePasswordHashParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

func (q *Queries) CreatePasswordHash(ctx context.Context, arg CreatePasswordHashParams) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, createPasswordHash, arg.UserID, arg.PasswordHash)
	var i UserPassword
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash FROM user_passwords WHERE user_id = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getPasswordHash, userID)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE user_passwords SET password_hash=$2, updated_at=now() WHERE user_id = $1 RETURNING user_id, password_hash, updated_at
`

type UpdatePasswordHashParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (UserPassword, error) {
	row := q.db.QueryRowContext(ctx, updatePasswordHash, arg.UserID, arg.PasswordHash)
	var i UserPassword
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}
